from __future__ import annotations

import argparse
import json
import math
import os
import re
import shutil
import unicodedata
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any

from pyrouge import Rouge155

_SENTENCE_BOUNDARY = re.compile(r"(?<=[.!?])\s+")
_WORK_DIR_MARKER = ".generated_by_evaluate_rouge"
_FILENAME_ID_WIDTH = 9
_ROUGE_BASE_PROTOCOL = "-c 95 -2 -1 -U -r 1000 -n 4 -w 1.2 -a"
_ROUGE_PROTOCOL = f"{_ROUGE_BASE_PROTOCOL} -m"
_DETAIL_PATTERN = re.compile(
    r"^(\d+)\s+ROUGE-(1|2|L)\s+Eval\s+(\d+)\.(\d+)\s+"
    r"R:([+\-0-9.eE]+)\s+P:([+\-0-9.eE]+)\s+F:([+\-0-9.eE]+)$"
)


def _canonical(value: Any) -> Any:
    if isinstance(value, str):
        return unicodedata.normalize("NFC", value)
    if isinstance(value, list):
        return [_canonical(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _canonical(item) for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))}
    return value


def _sentences(text: Any) -> list[str]:
    text = unicodedata.normalize("NFC", str(text))
    sentences: list[str] = []
    for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        sentences.extend(part.strip() for part in _SENTENCE_BOUNDARY.split(line.strip()) if part.strip())
    return sentences or [""]


def _reset_work_dir(work_dir: Path) -> None:
    if work_dir.exists():
        if not (work_dir / _WORK_DIR_MARKER).is_file():
            raise FileExistsError(f"Refusing to delete unrecognized directory: {work_dir}. Choose another --work-dir.")
        shutil.rmtree(work_dir)


def _references(value: Any) -> list[Any]:
    if isinstance(value, list):
        if not value:
            raise ValueError("Reference list cannot be empty")
        if len(value) > 26:
            raise ValueError("At most 26 references are supported per example")
        return value
    return [value]


def _prepare_data(
    predictions_file: Path,
    work_dir: Path,
    prediction_field: str,
    reference_field: str,
) -> list[dict[str, Any]]:
    _reset_work_dir(work_dir)
    system_dir = work_dir / "system"
    reference_dir = work_dir / "reference"
    system_dir.mkdir(parents=True)
    reference_dir.mkdir(parents=True)
    (work_dir / _WORK_DIR_MARKER).write_text(
        "Generated by src/evaluate/evaluate_rouge.py\n",
        encoding="utf-8",
    )

    bindings: list[dict[str, Any]] = []
    with predictions_file.open("r", encoding="utf-8") as handle:
        for line_number, raw in enumerate(handle, start=1):
            if not raw.strip():
                continue
            try:
                row = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at {predictions_file}:{line_number}") from exc
            if prediction_field not in row or reference_field not in row:
                raise ValueError(
                    f"Missing {prediction_field!r}/{reference_field!r} at {predictions_file}:{line_number}"
                )
            count = len(bindings)
            file_id = f"{count:0{_FILENAME_ID_WIDTH}d}"
            (system_dir / f"summary.{file_id}.txt").write_text(
                "\n".join(_sentences(row[prediction_field])) + "\n",
                encoding="utf-8",
            )
            for reference_index, reference in enumerate(_references(row[reference_field])):
                label = chr(ord("A") + reference_index)
                (reference_dir / f"summary.{label}.{file_id}.txt").write_text(
                    "\n".join(_sentences(reference)) + "\n",
                    encoding="utf-8",
                )
            bindings.append(
                {
                    "row_index": count,
                    "id": _canonical(row.get("id", count)),
                    "reference": _canonical(row[reference_field]),
                }
            )
    if not bindings:
        raise ValueError(f"No examples found in {predictions_file}")
    return bindings


def _pyrouge_version() -> str:
    try:
        return version("pyrouge")
    except PackageNotFoundError:
        return "unknown"


def _parse_per_example(raw_output: str, count: int) -> list[dict[str, Any]]:

    grouped: dict[int, dict[str, dict[str, float]]] = {}
    names = {"1": "rouge1", "2": "rouge2", "L": "rougeL"}
    for raw_line in raw_output.splitlines():
        match = _DETAIL_PATTERN.match(raw_line.strip())
        if match is None:
            continue
        system_id, order, raw_task_id, peer_id, recall, precision, f_score = match.groups()
        if system_id != "1" or peer_id != "1":
            raise ValueError(f"Unexpected detailed ROUGE system/peer ID: system={system_id} peer={peer_id}")
        task_id = int(raw_task_id)
        index = task_id - 1
        metric = names[order]
        values = {
            "recall": float(recall),
            "precision": float(precision),
            "f1": float(f_score),
        }
        if any(not math.isfinite(value) or not 0.0 <= value <= 1.0 for value in values.values()):
            raise ValueError(f"Invalid detailed ROUGE value for task={task_id} metric={metric}")
        if metric in grouped.setdefault(index, {}):
            raise ValueError(f"Duplicate detailed ROUGE score for row={index} metric={metric}")
        grouped[index][metric] = values

    expected_indices = list(range(count))
    if sorted(grouped) != expected_indices:
        raise ValueError(
            f"Detailed ROUGE IDs do not match prediction row order: expected 0..{count - 1}, got {sorted(grouped)[:10]}"
        )
    required = {"rouge1", "rouge2", "rougeL"}
    rows = []
    for index in expected_indices:
        if set(grouped[index]) != required:
            raise ValueError(f"Detailed ROUGE row {index} is missing metrics")
        rows.append({"row_index": index, "eval_task_id": index + 1, **grouped[index]})
    return rows


def _details_path(output_file: Path) -> Path:
    return output_file.with_name(f"{output_file.stem}.per_example.json")


def evaluate(
    predictions_file: Path,
    work_dir: Path,
    output_file: Path,
    prediction_field: str = "prediction",
    reference_field: str = "reference",
    write_details: bool = False,
) -> dict[str, Any]:
    predictions_file = predictions_file.expanduser().resolve()
    work_dir = work_dir.expanduser().resolve()
    output_file = output_file.expanduser().resolve()
    if not predictions_file.is_file():
        raise FileNotFoundError(f"Predictions JSONL not found: {predictions_file}")

    bindings = _prepare_data(
        predictions_file,
        work_dir,
        prediction_field,
        reference_field,
    )
    count = len(bindings)
    default_home = Path(__file__).resolve().parent / ".runtime/pyrouge-source/tools/ROUGE-1.5.5"
    rouge_home = Path(os.environ.get("PYROUGE_HOME_DIR", default_home)).resolve()
    rouge_script = rouge_home / "ROUGE-1.5.5.pl"
    if not rouge_script.is_file():
        raise FileNotFoundError(f"ROUGE-1.5.5.pl not found at {rouge_script}; set PYROUGE_HOME_DIR")
    if not os.access(rouge_script, os.X_OK):
        raise PermissionError(f"ROUGE script is not executable: chmod +x {rouge_script}")
    wordnet_database = rouge_home / "data/WordNet-2.0.exc.db"
    if not wordnet_database.exists():
        raise FileNotFoundError(f"WordNet-2.0 exception database not found: {wordnet_database}")

    local_perl = Path(__file__).resolve().parent / ".runtime/perl5/lib/perl5"
    if local_perl.is_dir():
        current = os.environ.get("PERL5LIB", "")
        os.environ["PERL5LIB"] = f"{local_perl}{os.pathsep}{current}" if current else str(local_perl)

    rouge = Rouge155(str(rouge_home))
    rouge.system_dir = str(work_dir / "system")
    rouge.model_dir = str(work_dir / "reference")
    rouge.system_filename_pattern = r"summary\.(\d+)\.txt"
    rouge.model_filename_pattern = r"summary\.[A-Z]\.#ID#\.txt"

    raw_output = rouge.convert_and_evaluate()
    raw_scores = rouge.output_to_dict(raw_output)
    result = {
        "rouge1": raw_scores["rouge_1_f_score"] * 100.0,
        "rouge2": raw_scores["rouge_2_f_score"] * 100.0,
        "rougeL": raw_scores["rouge_l_f_score"] * 100.0,
        "num_examples": count,
        "backend": f"Perl ROUGE-1.5.5 via pyrouge=={_pyrouge_version()}",
        "stemming": True,
        "pyrouge_default_args": _ROUGE_PROTOCOL,
        "prediction_field": prediction_field,
        "reference_field": reference_field,
        "predictions_file": str(predictions_file),
        "prepared_data_dir": str(work_dir),
        "rouge_home": str(rouge_home),
        "raw_scores": raw_scores,
    }
    if write_details:
        output_file.parent.mkdir(parents=True, exist_ok=True)
        detail_protocol = f"{_ROUGE_PROTOCOL} -d"
        detail_raw_output = rouge.evaluate(rouge_args=f"-e {rouge_home / 'data'} {_ROUGE_PROTOCOL} -d")
        detail_rows = _parse_per_example(detail_raw_output, count)
        for row, binding in zip(detail_rows, bindings, strict=True):
            row.update(
                {
                    "id": binding["id"],
                    "reference": binding["reference"],
                }
            )
        per_example_f1_mean = {
            metric: sum(row[metric]["f1"] for row in detail_rows) / count for metric in ("rouge1", "rouge2", "rougeL")
        }
        detail_file = _details_path(output_file)
        detail_raw_file = detail_file.with_suffix(".raw.txt")
        detail_raw_file.write_text(detail_raw_output, encoding="utf-8")
        detail_artifact = {
            "schema_version": "eviseq.perl_rouge155_details.v1",
            "num_examples": count,
            "backend": f"Perl ROUGE-1.5.5 via pyrouge=={_pyrouge_version()}",
            "headline_protocol": _ROUGE_PROTOCOL,
            "detail_protocol": detail_protocol,
            "prediction_field": prediction_field,
            "reference_field": reference_field,
            "predictions_file": str(predictions_file),
            "raw_detail_file": str(detail_raw_file),
            "per_example_f1_mean": per_example_f1_mean,
            "rows": detail_rows,
        }
        detail_file.write_text(
            json.dumps(detail_artifact, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        result["per_example_scores_file"] = str(detail_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(
        json.dumps(result, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    output_file.with_suffix(".raw.txt").write_text(raw_output, encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Calculate ROUGE-1/2/L F1 with official Perl ROUGE-1.5.5. "
            "The input must be JSONL with prediction and reference fields."
        )
    )
    parser.add_argument("predictions", type=Path, help="Prediction JSONL file")
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--prediction-field", default="prediction")
    parser.add_argument("--reference-field", default="reference")
    parser.add_argument(
        "--details",
        action="store_true",
        help="Also run Perl ROUGE with -d and save per-example scores for paired bootstrap",
    )
    args = parser.parse_args()
    predictions = args.predictions.expanduser().resolve()
    work_dir = args.work_dir or predictions.with_suffix(".rouge_data")
    output = args.output or predictions.with_suffix(".rouge155.json")
    result = evaluate(
        predictions,
        work_dir,
        output,
        args.prediction_field,
        args.reference_field,
        args.details,
    )
    print(f"ROUGE-1={result['rouge1']:.3f} ROUGE-2={result['rouge2']:.3f} ROUGE-L={result['rougeL']:.3f}")
    print(f"Saved metrics: {output.resolve()}")
    print(f"Saved raw output: {output.resolve().with_suffix('.raw.txt')}")
    if args.details:
        print(f"Saved per-example scores: {_details_path(output.resolve())}")


if __name__ == "__main__":
    main()
